name: Fetch Air Quality Data

on:
  schedule:
    - cron: "0 * * * *"   # كل ساعة
  workflow_dispatch:       # تشغيل يدوي من زر Run workflow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run script
        env:
          AQI_TOKEN: ${{ secrets.AQI_TOKEN }}
        run: python fetch.py
      - name: Commit and push changes
        run: |
          git config --global user.email "nourelislem.tahir@gmail.com"
          git config --global user.name "Cryyufstal"
          git add data/air_quality.csv
          git commit -m "Update data [skip ci]" || echo "No changes"
          git push
